// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: proto/gobox.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLastUpdateTimeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GetLastUpdateTimeResult) Reset() {
	*x = GetLastUpdateTimeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gobox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLastUpdateTimeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastUpdateTimeResult) ProtoMessage() {}

func (x *GetLastUpdateTimeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastUpdateTimeResult.ProtoReflect.Descriptor instead.
func (*GetLastUpdateTimeResult) Descriptor() ([]byte, []int) {
	return file_proto_gobox_proto_rawDescGZIP(), []int{0}
}

func (x *GetLastUpdateTimeResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SendFileInfoInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName    string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileId      int64  `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	IsDirectory bool   `protobuf:"varint,3,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	Size        int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ModTime     int64  `protobuf:"varint,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
}

func (x *SendFileInfoInput) Reset() {
	*x = SendFileInfoInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gobox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFileInfoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileInfoInput) ProtoMessage() {}

func (x *SendFileInfoInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileInfoInput.ProtoReflect.Descriptor instead.
func (*SendFileInfoInput) Descriptor() ([]byte, []int) {
	return file_proto_gobox_proto_rawDescGZIP(), []int{1}
}

func (x *SendFileInfoInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SendFileInfoInput) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *SendFileInfoInput) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *SendFileInfoInput) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SendFileInfoInput) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

type SendFileInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendChunkIds bool `protobuf:"varint,1,opt,name=send_chunk_ids,json=sendChunkIds,proto3" json:"send_chunk_ids,omitempty"`
}

func (x *SendFileInfoResponse) Reset() {
	*x = SendFileInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gobox_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileInfoResponse) ProtoMessage() {}

func (x *SendFileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobox_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileInfoResponse.ProtoReflect.Descriptor instead.
func (*SendFileInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_gobox_proto_rawDescGZIP(), []int{2}
}

func (x *SendFileInfoResponse) GetSendChunkIds() bool {
	if x != nil {
		return x.SendChunkIds
	}
	return false
}

type SendFileChunksInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId *ChunkID `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data    []byte   `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *SendFileChunksInput) Reset() {
	*x = SendFileChunksInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gobox_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFileChunksInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileChunksInput) ProtoMessage() {}

func (x *SendFileChunksInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobox_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileChunksInput.ProtoReflect.Descriptor instead.
func (*SendFileChunksInput) Descriptor() ([]byte, []int) {
	return file_proto_gobox_proto_rawDescGZIP(), []int{3}
}

func (x *SendFileChunksInput) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *SendFileChunksInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChunkID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId      int64 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkNumber int64 `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
}

func (x *ChunkID) Reset() {
	*x = ChunkID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gobox_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkID) ProtoMessage() {}

func (x *ChunkID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobox_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkID.ProtoReflect.Descriptor instead.
func (*ChunkID) Descriptor() ([]byte, []int) {
	return file_proto_gobox_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkID) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *ChunkID) GetChunkNumber() int64 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

type SendFileChunksDataInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId *ChunkID `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Data    []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendFileChunksDataInput) Reset() {
	*x = SendFileChunksDataInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gobox_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFileChunksDataInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileChunksDataInput) ProtoMessage() {}

func (x *SendFileChunksDataInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobox_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileChunksDataInput.ProtoReflect.Descriptor instead.
func (*SendFileChunksDataInput) Descriptor() ([]byte, []int) {
	return file_proto_gobox_proto_rawDescGZIP(), []int{5}
}

func (x *SendFileChunksDataInput) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *SendFileChunksDataInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendFileChunksDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId []byte `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
}

func (x *SendFileChunksDataRequest) Reset() {
	*x = SendFileChunksDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gobox_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFileChunksDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileChunksDataRequest) ProtoMessage() {}

func (x *SendFileChunksDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobox_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileChunksDataRequest.ProtoReflect.Descriptor instead.
func (*SendFileChunksDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_gobox_proto_rawDescGZIP(), []int{6}
}

func (x *SendFileChunksDataRequest) GetChunkId() []byte {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

type Null struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Null) Reset() {
	*x = Null{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gobox_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobox_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_proto_gobox_proto_rawDescGZIP(), []int{7}
}

var File_proto_gobox_proto protoreflect.FileDescriptor

var file_proto_gobox_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x22, 0x37, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x22, 0x9b, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x3c, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x6e,
	0x64, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x73, 0x22,
	0x62, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x62, 0x6f, 0x78,
	0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x07, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x12, 0x17,
	0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x58, 0x0a, 0x17, 0x53, 0x65,
	0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x36, 0x0a, 0x19, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x22, 0x06, 0x0a, 0x04,
	0x4e, 0x75, 0x6c, 0x6c, 0x32, 0xe4, 0x02, 0x0a, 0x05, 0x47, 0x6f, 0x42, 0x6f, 0x78, 0x12, 0x42,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x0b, 0x2e, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x4e, 0x75, 0x6c, 0x6c,
	0x1a, 0x1e, 0x2e, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x18, 0x2e, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1b, 0x2e, 0x67,
	0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0e, 0x53,
	0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x1a, 0x2e,
	0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0b, 0x2e, 0x67, 0x6f, 0x62, 0x6f,
	0x78, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x00, 0x28, 0x01, 0x12, 0x5c, 0x0a, 0x12, 0x53, 0x65,
	0x6e, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x20, 0x2e, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x13, 0x49, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x0b, 0x2e, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x1a, 0x0b, 0x2e, 0x67,
	0x6f, 0x62, 0x6f, 0x78, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x64, 0x72, 0x69, 0x61, 0x6e,
	0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x62, 0x6f, 0x78, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gobox_proto_rawDescOnce sync.Once
	file_proto_gobox_proto_rawDescData = file_proto_gobox_proto_rawDesc
)

func file_proto_gobox_proto_rawDescGZIP() []byte {
	file_proto_gobox_proto_rawDescOnce.Do(func() {
		file_proto_gobox_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gobox_proto_rawDescData)
	})
	return file_proto_gobox_proto_rawDescData
}

var file_proto_gobox_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_gobox_proto_goTypes = []interface{}{
	(*GetLastUpdateTimeResult)(nil),   // 0: gobox.GetLastUpdateTimeResult
	(*SendFileInfoInput)(nil),         // 1: gobox.SendFileInfoInput
	(*SendFileInfoResponse)(nil),      // 2: gobox.SendFileInfoResponse
	(*SendFileChunksInput)(nil),       // 3: gobox.SendFileChunksInput
	(*ChunkID)(nil),                   // 4: gobox.ChunkID
	(*SendFileChunksDataInput)(nil),   // 5: gobox.SendFileChunksDataInput
	(*SendFileChunksDataRequest)(nil), // 6: gobox.SendFileChunksDataRequest
	(*Null)(nil),                      // 7: gobox.Null
}
var file_proto_gobox_proto_depIdxs = []int32{
	4, // 0: gobox.SendFileChunksInput.chunk_id:type_name -> gobox.ChunkID
	4, // 1: gobox.SendFileChunksDataInput.chunk_id:type_name -> gobox.ChunkID
	7, // 2: gobox.GoBox.GetLastUpdateTime:input_type -> gobox.Null
	1, // 3: gobox.GoBox.SendFileInfo:input_type -> gobox.SendFileInfoInput
	3, // 4: gobox.GoBox.SendFileChunks:input_type -> gobox.SendFileChunksInput
	5, // 5: gobox.GoBox.SendFileChunksData:input_type -> gobox.SendFileChunksDataInput
	7, // 6: gobox.GoBox.InitialSyncComplete:input_type -> gobox.Null
	0, // 7: gobox.GoBox.GetLastUpdateTime:output_type -> gobox.GetLastUpdateTimeResult
	2, // 8: gobox.GoBox.SendFileInfo:output_type -> gobox.SendFileInfoResponse
	7, // 9: gobox.GoBox.SendFileChunks:output_type -> gobox.Null
	6, // 10: gobox.GoBox.SendFileChunksData:output_type -> gobox.SendFileChunksDataRequest
	7, // 11: gobox.GoBox.InitialSyncComplete:output_type -> gobox.Null
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_gobox_proto_init() }
func file_proto_gobox_proto_init() {
	if File_proto_gobox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gobox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLastUpdateTimeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gobox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFileInfoInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gobox_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFileInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gobox_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFileChunksInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gobox_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChunkID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gobox_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFileChunksDataInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gobox_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFileChunksDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gobox_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Null); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_gobox_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gobox_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gobox_proto_goTypes,
		DependencyIndexes: file_proto_gobox_proto_depIdxs,
		MessageInfos:      file_proto_gobox_proto_msgTypes,
	}.Build()
	File_proto_gobox_proto = out.File
	file_proto_gobox_proto_rawDesc = nil
	file_proto_gobox_proto_goTypes = nil
	file_proto_gobox_proto_depIdxs = nil
}
